
'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("fb17c337-9b43-4081-82bb-aca4fdd6ac69")>
#Region "Contextes"

''' <summary>
''' Aucune documentation sur les métadonnées n'est disponible.
''' </summary>
Public Partial Class testentityEntities
    Inherits ObjectContext

    #Region "Constructeurs"

    ''' <summary>
    ''' Initialise un nouvel objet testentityEntities à l'aide de la chaîne de connexion trouvée dans la section 'testentityEntities' du fichier de configuration d'application.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=testentityEntities", "testentityEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialisez un nouvel objet testentityEntities.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "testentityEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialisez un nouvel objet testentityEntities.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "testentityEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Méthodes partielles"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "Propriétés ObjectSet"

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    Public ReadOnly Property user() As ObjectSet(Of user)
        Get
            If (_user Is Nothing) Then
                _user = MyBase.CreateObjectSet(Of user)("user")
            End If
            Return _user
        End Get
    End Property

    Private _user As ObjectSet(Of user)

    #End Region

    #Region "Méthodes AddTo"

    ''' <summary>
    ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet user. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
    ''' </summary>
    Public Sub AddTouser(ByVal user As user)
        MyBase.AddObject("user", user)
    End Sub

    #End Region

End Class

#End Region

#Region "Entités"

''' <summary>
''' Aucune documentation sur les métadonnées n'est disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="testentityModel", Name:="user")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class user
    Inherits EntityObject
    #Region "Méthode de fabrique"

    ''' <summary>
    ''' Créez un nouvel objet user.
    ''' </summary>
    ''' <param name="numero">Valeur initiale de la propriété numero.</param>
    ''' <param name="login">Valeur initiale de la propriété login.</param>
    ''' <param name="password">Valeur initiale de la propriété password.</param>
    ''' <param name="email">Valeur initiale de la propriété email.</param>
    Public Shared Function Createuser(numero As Global.System.Int32, login As Global.System.String, password As Global.System.String, email As Global.System.String) As user
        Dim user as user = New user
        user.numero = numero
        user.login = login
        user.password = password
        user.email = email
        Return user
    End Function

    #End Region

    #Region "Propriétés primitives"

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property numero() As Global.System.Int32
        Get
            Return _numero
        End Get
        Set
            If (_numero <> Value) Then
                OnnumeroChanging(value)
                ReportPropertyChanging("numero")
                _numero = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("numero")
                OnnumeroChanged()
            End If
        End Set
    End Property

    Private _numero As Global.System.Int32
    Private Partial Sub OnnumeroChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnnumeroChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property login() As Global.System.String
        Get
            Return _login
        End Get
        Set
            OnloginChanging(value)
            ReportPropertyChanging("login")
            _login = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("login")
            OnloginChanged()
        End Set
    End Property

    Private _login As Global.System.String
    Private Partial Sub OnloginChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnloginChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property password() As Global.System.String
        Get
            Return _password
        End Get
        Set
            OnpasswordChanging(value)
            ReportPropertyChanging("password")
            _password = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("password")
            OnpasswordChanged()
        End Set
    End Property

    Private _password As Global.System.String
    Private Partial Sub OnpasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpasswordChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property email() As Global.System.String
        Get
            Return _email
        End Get
        Set
            OnemailChanging(value)
            ReportPropertyChanging("email")
            _email = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("email")
            OnemailChanged()
        End Set
    End Property

    Private _email As Global.System.String
    Private Partial Sub OnemailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnemailChanged()
    End Sub

    #End Region

End Class

#End Region


